kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: "mongodb"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    name: "mongodb"
  template:
    metadata:
      name: "mongodb"
      labels:
        name: "mongodb"
    spec:
      containers:
      - name: mongodb
        image: >-
          172.30.1.1:5000/openshift/mongodb@sha256:2dbca138ad89de50c84befe6fefc9293ce4437904b84a4b8200b649594e5a4f1
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name | quote }}
              key: database-user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name | quote }}
              key: database-password
        - name: MONGODB_DATABASE
          value: "sampledb"
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name | quote }}
              key: database-admin-password
        readinessProbe:
          timeoutSeconds: 3
          periodSeconds: 3
          initialDelaySeconds: 30
          exec:
            command:
            - /bin/sh
            - '-i'
            - '-c'
            - >-
              mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval="quit()"
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 30
          tcpSocket:
            port: 27017
        resources:
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: "mongodb-data"
          mountPath: "/var/lib/mongodb/data"
      volumes:
      - name: "mongodb-data"
        persistentVolumeClaim:
          claimName: "mongodb"
